csvfile = open("NamesTest.csv", "r")
fakeNames = csvfile.read()
row = csvfile.readline()
htmlFile = open("NamesTestHtml.html", "w")
htmlFile.write("<html>")
htmlFile.write("<head>")
htmlFile.write("<title>TEST</title>")
htmlFile.write("</head>")
htmlFile.write("<body>")
htmlFile.write("<center>")
htmlFile.write("<table border = 1 style='border: 1px solid blue; color: white; Background-color: black; margin-top: 30px'>")
for line in fakeNames:
        htmlFile.write("<tr>")
        #for i in range(withinnthe row):
        htmlFile.write("<td>")
        htmlFile.write(line)
        htmlFile.write("</td>")
        htmlFile.write("</tr>")
htmlFile.write("</table>")
htmlFile.write("</center>")
htmlFile.write("</body>")
htmlFile.write("</html>")
htmlFile.close()
